// ─────────────────────────────────────────────
//  Code Generator — walks the AST and emits Embedded C
// ─────────────────────────────────────────────

import { TARGETS } from "./targets.js";

export class CodeGen {
  constructor(targetKey = "arduino") {
    this.lines        = [];
    this.depth        = 0;
    this.symbols      = {};
    this.needsSerial  = false;
    this.needsPwm     = false;
    this.pwmPins      = new Set();
    this.warnings     = [];
    this.funcNames    = new Set();
    this.T            = TARGETS[targetKey];
    this.targetKey    = targetKey;
  }

  pad()    { return "    ".repeat(this.depth); }
  emit(s)  { this.lines.push(this.pad() + s); }
  blank()  { this.lines.push(""); }

  // ── Type mapping ────────────────────────────
  mapType(t) {
    if (!t) return "void";
    const m = {
      int: "int", float: "float", bool: "bool",
      str: "const char*", void: "void",
      "list[int]": "int*", "list[float]": "float*", "list[bool]": "bool*",
    };
    return m[t] || "int";
  }

  inferType(node) {
    if (!node) return "int";
    if (node.type === "Num")    return node.val.includes(".") ? "float" : "int";
    if (node.type === "Bool")   return "bool";
    if (node.type === "Str")    return "const char*";
    if (node.type === "Name")   return this.symbols[node.name] || "int";
    if (node.type === "BinOp") {
      const lt = this.inferType(node.l), rt = this.inferType(node.r);
      return (lt === "float" || rt === "float") ? "float" : "int";
    }
    if (node.type === "Call") {
      if (["analogRead","digitalRead","millis","micros"].includes(node.name)) return "int";
      if (node.name === "float") return "float";
      if (node.name === "bool")  return "bool";
      return "int";
    }
    return "int";
  }

  // ── Pre-scan to detect serial / PWM usage ───
  scanNodes(nodes) {
    if (!nodes) return;
    for (const n of nodes) {
      if (!n) continue;
      if (n.type === "ExprStmt" && n.expr?.type === "Call") {
        if (n.expr.name === "print") this.needsSerial = true;
        if (n.expr.name === "analogWrite") {
          this.needsPwm = true;
          if (n.expr.args[0]?.type === "Num") this.pwmPins.add(n.expr.args[0].val);
        }
      }
      if (n.type === "FuncDef")  this.funcNames.add(n.name);
      if (n.body)     this.scanNodes(n.body);
      if (n.elseBody) this.scanNodes(n.elseBody);
      if (n.elifs)    n.elifs.forEach(e => this.scanNodes(e.body));
    }
  }

  // ── Top-level entry ─────────────────────────
  generate(ast) {
    this.scanNodes(ast.body);
    const T = this.T;

    // File header
    const header = [
      "// ─────────────────────────────────────────────",
      "// Generated by PyEmbed Compiler",
      `// Target: ${T.label} (${T.sub})`,
      `// Logic voltage: ${T.voltage}  |  ADC: ${T.adcBits}-bit (0–${T.adcMax})`,
      `// Serial baud: ${T.serialBaud}`,
      "// ─────────────────────────────────────────────",
      ...T.headers,
      "",
      ...T.notes,
      "",
    ];

    // ESP32: PWM globals
    if (this.targetKey === "esp32" && this.needsPwm) {
      header.push("// PWM channel config (ledc)");
      header.push("const int PWM_CHANNEL = 0;");
      header.push("const int PWM_FREQ    = 5000;");
      header.push("const int PWM_RES     = 8;");
      header.push("");
    }

    // STM32: extern HAL handles
    if (this.targetKey === "stm32") {
      header.push("extern UART_HandleTypeDef huart2;");
      if (this.needsPwm) header.push("extern TIM_HandleTypeDef htim2;");
      header.push("extern ADC_HandleTypeDef hadc1;");
      header.push("");
    }

    const helpers  = ast.body.filter(n => n.type === "FuncDef" && n.name !== "setup" && n.name !== "loop");
    const setupFn  = ast.body.find(n  => n.type === "FuncDef" && n.name === "setup");
    const loopFn   = ast.body.find(n  => n.type === "FuncDef" && n.name === "loop");
    const topStmts = ast.body.filter(n => n.type !== "FuncDef");

    // Forward declarations
    if (helpers.length > 0) {
      this.emit("// ── Forward Declarations ──────────────────");
      for (const fn of helpers) {
        const ret = this.mapType(fn.returnType);
        const ps  = fn.params.map(p => `${this.mapType(p.ptype)} ${p.name}`).join(", ");
        this.emit(`${ret} ${fn.name}(${ps});`);
      }
      this.blank();
    }

    for (const fn of helpers) { this.genFunc(fn); this.blank(); }

    if (setupFn) {
      this.genFunc(setupFn);
    } else {
      this.emit("void setup() {");
      this.depth++;
      this.emitSetupInit();
      for (const s of topStmts) this.genStmt(s);
      if (topStmts.length === 0) this.emit("// Initialization code here");
      this.depth--;
      this.emit("}");
    }
    this.blank();

    if (loopFn) {
      this.genFunc(loopFn);
    } else {
      this.emit(this.targetKey === "stm32" ? "void app_loop() {" : "void loop() {");
      this.depth++;
      this.emit("// Main loop code here");
      this.depth--;
      this.emit("}");
    }

    return [...header, ...this.lines].join("\n");
  }

  emitSetupInit() {
    const T = this.T;
    if (this.needsSerial) this.emit(T.serialBegin(T.serialBaud));
    if (this.targetKey === "esp32" && this.needsPwm) {
      this.emit(`ledcSetup(PWM_CHANNEL, PWM_FREQ, PWM_RES);`);
      for (const pin of this.pwmPins) this.emit(`ledcAttachPin(${pin}, PWM_CHANNEL);`);
    }
    if (this.targetKey === "stm32" && this.needsPwm)
      this.emit(`HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);`);
  }

  // ── Function generation ──────────────────────
  genFunc(node) {
    const ret = this.mapType(node.returnType || "void");
    const ps  = node.params.map(p => {
      this.symbols[p.name] = this.mapType(p.ptype);
      return `${this.mapType(p.ptype)} ${p.name}`;
    }).join(", ");

    if (this.targetKey === "stm32" && node.name === "loop") {
      this.emit("// STM32: place loop body inside while(1) in main()");
      this.emit("void app_loop() {");
    } else {
      this.emit(`${ret} ${node.name}(${ps}) {`);
    }
    this.depth++;
    if (node.name === "setup") this.emitSetupInit();
    for (const s of node.body) this.genStmt(s);
    this.depth--;
    this.emit("}");
  }

  // ── Statement generation ─────────────────────
  genStmt(node) {
    switch (node.type) {
      case "AnnAssign": {
        const ct = this.mapType(node.vtype);
        this.symbols[node.target] = ct;
        this.emit(node.val
          ? `${ct} ${node.target} = ${this.genExpr(node.val)};`
          : `${ct} ${node.target};`);
        break;
      }
      case "Assign": {
        if (this.symbols[node.target]) {
          this.emit(`${node.target} = ${this.genExpr(node.val)};`);
        } else {
          const ct = this.inferType(node.val);
          this.symbols[node.target] = ct;
          this.emit(`${ct} ${node.target} = ${this.genExpr(node.val)};`);
        }
        break;
      }
      case "AugAssign":
        this.emit(`${node.target} ${node.op} ${this.genExpr(node.val)};`);
        break;
      case "ExprStmt":
        this.emit(`${this.genExpr(node.expr)};`);
        break;
      case "Return":
        this.emit(node.val ? `return ${this.genExpr(node.val)};` : "return;");
        break;
      case "Pass":     this.emit("// pass"); break;
      case "Break":    this.emit("break;");  break;
      case "Continue": this.emit("continue;"); break;
      case "If": {
        this.emit(`if (${this.genExpr(node.test)}) {`);
        this.depth++;
        node.body.forEach(s => this.genStmt(s));
        this.depth--;
        this.emit("}");
        for (const el of node.elifs) {
          this.emit(`else if (${this.genExpr(el.test)}) {`);
          this.depth++;
          el.body.forEach(s => this.genStmt(s));
          this.depth--;
          this.emit("}");
        }
        if (node.elseBody) {
          this.emit("else {");
          this.depth++;
          node.elseBody.forEach(s => this.genStmt(s));
          this.depth--;
          this.emit("}");
        }
        break;
      }
      case "While": {
        const cond = node.test.type === "Bool" && node.test.val === "True"
          ? "1" : this.genExpr(node.test);
        this.emit(`while (${cond}) {`);
        this.depth++;
        node.body.forEach(s => this.genStmt(s));
        this.depth--;
        this.emit("}");
        break;
      }
      case "For": {
        if (node.iter.type === "Call" && node.iter.name === "range") {
          const a = node.iter.args;
          if (a.length === 1)
            this.emit(`for (int ${node.target} = 0; ${node.target} < ${this.genExpr(a[0])}; ${node.target}++) {`);
          else if (a.length === 2)
            this.emit(`for (int ${node.target} = ${this.genExpr(a[0])}; ${node.target} < ${this.genExpr(a[1])}; ${node.target}++) {`);
          else
            this.emit(`for (int ${node.target} = ${this.genExpr(a[0])}; ${node.target} < ${this.genExpr(a[1])}; ${node.target} += ${this.genExpr(a[2])}) {`);
          this.symbols[node.target] = "int";
        } else {
          const an = node.iter.type === "Name" ? node.iter.name : "arr";
          this.emit(`for (int _i = 0; _i < sizeof(${an})/sizeof(${an}[0]); _i++) {`);
          this.emit(`    int ${node.target} = ${an}[_i];`);
        }
        this.depth++;
        node.body.forEach(s => this.genStmt(s));
        this.depth--;
        this.emit("}");
        break;
      }
      case "FuncDef":
        this.genFunc(node);
        break;
      default:
        this.emit(`// [unhandled node: ${node.type}]`);
    }
  }

  // ── Expression generation ────────────────────
  genExpr(node) {
    if (!node) return "";
    switch (node.type) {
      case "Num":    return node.val;
      case "Bool":   return node.val === "True" ? "1" : node.val === "False" ? "0" : "NULL";
      case "Str":    return `"${node.val}"`;
      case "Name":   return this.T.mapPin(node.name);
      case "Index":  return `${node.obj}[${this.genExpr(node.idx)}]`;
      case "UnaryOp": return `${node.op}(${this.genExpr(node.v)})`;
      case "BinOp": {
        const lp = node.l.type === "BinOp" ? `(${this.genExpr(node.l)})` : this.genExpr(node.l);
        const rp = node.r.type === "BinOp" ? `(${this.genExpr(node.r)})` : this.genExpr(node.r);
        if (node.op === "pow") return `pow(${lp}, ${rp})`;
        return `${lp} ${node.op} ${rp}`;
      }
      case "Call": return this.genCall(node);
      default: return `/* ? ${node.type} */`;
    }
  }

  genCall(node) {
    const args = node.args.map(a => this.genExpr(a));

    if (node.name === "print")
      return this.targetKey === "stm32"
        ? `HAL_UART_Transmit(&huart2, (uint8_t*)${args[0]}, strlen(${args[0]}), HAL_MAX_DELAY)`
        : `Serial.println(${args.join(", ")})`;

    if (node.name === "digitalWrite") {
      if (this.targetKey === "stm32") {
        const v = (args[1] === "HIGH" || args[1] === "1") ? "GPIO_PIN_SET" : "GPIO_PIN_RESET";
        return `HAL_GPIO_WritePin(GPIOA, GPIO_PIN_${args[0]}, ${v})`;
      }
      return `digitalWrite(${args.join(", ")})`;
    }
    if (node.name === "digitalRead")
      return this.targetKey === "stm32"
        ? `HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_${args[0]})`
        : `digitalRead(${args[0]})`;

    if (node.name === "analogRead")
      return this.targetKey === "stm32"
        ? `HAL_ADC_GetValue(&hadc1) /* CH${args[0]} */`
        : `analogRead(${args[0]})`;

    if (node.name === "analogWrite") {
      if (this.targetKey === "esp32")  return `ledcWrite(PWM_CHANNEL, ${args[1]})`;
      if (this.targetKey === "stm32")  return `__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, ${args[1]})`;
      return `analogWrite(${args.join(", ")})`;
    }
    if (node.name === "pinMode")
      return this.targetKey === "stm32"
        ? `/* pinMode(${args.join(",")}) → configure via CubeMX */`
        : `pinMode(${args.join(", ")})`;

    if (node.name === "delay")
      return this.targetKey === "stm32" ? `HAL_Delay(${args[0]})` : `delay(${args[0]})`;

    if (node.name === "delayMicroseconds")
      return this.targetKey === "stm32" ? `DWT_Delay_us(${args[0]})` : `delayMicroseconds(${args[0]})`;

    if (node.name === "millis")
      return this.targetKey === "stm32" ? `HAL_GetTick()` : `millis()`;

    if (node.name === "micros")
      return this.targetKey === "stm32"
        ? `(DWT->CYCCNT / (SystemCoreClock / 1000000))` : `micros()`;

    if (node.name === "tone") {
      if (this.targetKey === "esp32")  return `ledcWriteTone(PWM_CHANNEL, ${args[1]})`;
      if (this.targetKey === "stm32")  return `/* tone(${args.join(",")}) → configure TIM PWM */`;
      return `tone(${args.join(", ")})`;
    }
    if (node.name === "noTone") {
      if (this.targetKey === "esp32")  return `ledcWriteTone(PWM_CHANNEL, 0)`;
      if (this.targetKey === "stm32")  return `__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, 0)`;
      return `noTone(${args[0]})`;
    }
    if (node.name === "pulseIn")
      return this.targetKey === "stm32"
        ? `/* pulseIn → use TIM input capture */` : `pulseIn(${args.join(", ")})`;

    // Built-in casts & math
    if (node.name === "int")   return `(int)(${args[0]})`;
    if (node.name === "float") return `(float)(${args[0]})`;
    if (node.name === "bool")  return `(bool)(${args[0]})`;
    if (node.name === "abs")   return `abs(${args[0]})`;
    if (node.name === "min")   return `min(${args.join(", ")})`;
    if (node.name === "max")   return `max(${args.join(", ")})`;
    if (node.name === "len")   return `sizeof(${args[0]})`;
    if (node.name === "str")   return `String(${args[0]})`;

    return `${node.name}(${args.join(", ")})`;
  }
}
