// Hero — landing section with code card preview

const PY_DEMO = `<span class="pe-kw">def</span> <span class="pe-fn">blink_led</span>(pin: <span class="pe-ty">int</span>, times: <span class="pe-ty">int</span>):
    <span class="pe-cm"># Blink LED on given pin</span>
    ms: <span class="pe-ty">int</span> = 500
    <span class="pe-kw">for</span> i <span class="pe-kw">in</span> range(times):
        <span class="pe-fn">digitalWrite</span>(pin, HIGH)
        <span class="pe-fn">delay</span>(ms)
        <span class="pe-fn">digitalWrite</span>(pin, LOW)
        <span class="pe-fn">delay</span>(ms)`;

const C_DEMO = `<span class="pe-ty">#include</span> &lt;Arduino.h&gt;
<span class="pe-kw">void</span> <span class="pe-fn">blink_led</span>(<span class="pe-kw">int</span> pin, <span class="pe-kw">int</span> times) {
    <span class="pe-cm">// Generated by PyEmbed</span>
    <span class="pe-kw">int</span> ms = 500;
    <span class="pe-kw">for</span>(<span class="pe-kw">int</span> i=0; i&lt;times; i++) {
        <span class="pe-fn">digitalWrite</span>(pin, HIGH);
        <span class="pe-fn">delay</span>(ms);
        <span class="pe-fn">digitalWrite</span>(pin, LOW);
        <span class="pe-fn">delay</span>(ms);
    }
}`;

export default function Hero({ onGoCompiler, onGoArchitecture }) {
  return (
    <section className="hero">
      {/* Left — text content */}
      <div className="hero-l">
        <div className="hero-overline">
          <span className="blink-dot" />
          Python → Embedded C Compiler
        </div>

        <h1 className="hero-title">
          Python,<br />
          <em>Compiled</em><br />
          for Hardware.
        </h1>

        <p className="hero-sub">
          PyEmbed translates a statically-typed Python subset into optimized
          Embedded C — making IoT programming accessible without sacrificing
          performance or safety.
        </p>

        <div className="hero-btns">
          <button className="btn-dark" onClick={onGoCompiler}>
            Explore the Compiler
          </button>
          <button className="btn-outline" onClick={onGoArchitecture}>
            View Architecture →
          </button>
        </div>

        <div className="hero-stats">
          {[["5", "Stages"], ["3", "MCU Targets"], ["13", "Examples"]].map(([n, l]) => (
            <div className="hstat" key={l}>
              <span className="hstat-n">{n}</span>
              <span className="hstat-l">{l}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Right — animated code card */}
      <div className="hero-r">
        <div className="code-card">
          <div className="cpanel">
            <div className="cphead">
              <span className="cdot cdot-g" />
              <span className="clbl">PYTHON INPUT</span>
            </div>
            <div className="cblock" dangerouslySetInnerHTML={{ __html: PY_DEMO }} />
          </div>
          <div className="cdivider">
            <span className="cdiv-arrow">⟶ compiled by PyEmbed ⟶</span>
          </div>
          <div className="cpanel">
            <div className="cphead">
              <span className="cdot cdot-b" />
              <span className="clbl">EMBEDDED C OUTPUT</span>
            </div>
            <div className="cblock" dangerouslySetInnerHTML={{ __html: C_DEMO }} />
          </div>
        </div>
      </div>
    </section>
  );
}
